## Full Stack DL

> Notes on course by Neuralearn.ai - https://www.youtube.com/playlist?list=PL2L83ZcMO-5O7zNycUkS5WLgr33J3QxMK

---

### Basics

In [ ]:
import numpy as np
import tensorflow as tf

In [5]:
tf.random.set_seed(13)

In [ ]:
tf.AggregationMethod(

In [3]:
print (tf.random.uniform(shape=(3, ), minval=0, maxval=9, dtype=tf.float16))

tf.Tensor([7.508 7.832 6.434], shape=(3,), dtype=float16)


In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)
tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


In [5]:
tensor_one_d = tf.constant([2,0.,-3,8,90],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool) # negative values also get casted to True
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [6]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print (tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


A 2D tesnor is made up of stacking several 1D tensors

So the way to understand the shape:
- how many 1d tesnors? - 4
- within each 1D tensor, how many 0D tensors? - 3

So shape is `4,3`

In [7]:
tensor_three_d = tf.constant([
    [
        [1,2,0],
        [3,5,-1],
        [1,5,6],
        [2,3,8]
    ],

    [
        [1,2,0],
        [3,5,-1],
        [1,5,6],
        [2,3,8]
    ]
])

print (tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)


- 2 2D tensors
- each contains 4 1D tensor
- each contains 3 0D tensors

so shape `(2,4,3)`

In [8]:
matrix = tf.constant([[1, 2, 3], [1, 2, 3]])  # Rank-2 tensor
print (matrix.shape)
print(tf.rank(matrix))  # Output: 2

(2, 3)
tf.Tensor(2, shape=(), dtype=int32)


Random number generators:

In [9]:
g = tf.random.Generator.from_seed(seed=13)

In [10]:
g.uniform(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7452506 , 0.41762006, 0.8173511 ],
       [0.20117116, 0.6457157 , 0.16484237]], dtype=float32)>

In [11]:
g.uniform(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.9882078 , 0.76806545, 0.25653362],
       [0.7027086 , 0.1989007 , 0.72429776]], dtype=float32)>

In [12]:
tf.constant([[1,2], [3,4]], dtype=tf.uint8)

<tf.Tensor: shape=(2, 2), dtype=uint8, numpy=
array([[1, 2],
       [3, 4]], dtype=uint8)>

In [13]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
# print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)


This basically works by broadcasting:

![](https://imgur.com/SiAj5R1.png)

In [14]:
print(tf.math.multiply(x_1, x_2))

tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [15]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print (tf.argmax(x_argmax, axis=1))

tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [16]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [17]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y) # again works by broadcasting 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

`reduce_{stat}` computes {stat} across a certain dimension

In [18]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

(4, 3)


In [19]:
tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=True) # keepdims preserves the initial no of dimensions

<tf.Tensor: shape=(1, 3), dtype=float16, numpy=array([[  7.,  11., 114.]], dtype=float16)>

In [20]:
x = tf.constant([1,4,1,2,6,7,3])
tf.math.top_k(x, k=2).values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [21]:
tf.math.top_k(x, k=2).indices

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 4], dtype=int32)>

In [22]:
tf.math.top_k(tensor_two_d, k=2).values

<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>

In [23]:
tf.math.top_k(tensor_two_d, k=2).indices

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>

### Linalg

In [24]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
tf.linalg.matmul(x_1, x_2) # (will not work - incompatible shapes)

In [26]:
x_1 * x_2 # normal mul (element wise)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[35., 21., 42., 42., 28., 42.],
       [25., 15., 30., 30., 20., 30.],
       [15.,  9., 18., 18., 12., 18.]], dtype=float32)>

In [ ]:
x_1 @ x_2 # mat mul (will not work - incompatible shapes)

#### 3D matrix multiplication

- think of it like a batch mat mul



In [36]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])

print (a)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [37]:
b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
print (b)

tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)


2, (2, 3) x 2, (3, 2) = 2, (2, 3) x (3, 2) = 2, (2, 2)

Two 2x3 matrices 

Two 3x2 matrices

Each 2x3 matrix is multiplied with a 3x2 matrix to give a 2x2 matrix

In [38]:
c = tf.matmul(a, b)
print (c)

tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)


In [39]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])


print (x_1.shape, x_2.shape, x_3.shape)

(1, 3) (3, 2) (2, 4)


In [42]:
tf.linalg.matmul(x_2, x_1, transpose_a=True, transpose_b=True) # x_2^T . x_1^T

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 7],
       [12]], dtype=int32)>

In [ ]:
tf.linalg.matmul(
    x_3, x_2, transpose_a=True, transpose_b=True, adjoint_a=False, adjoint_b=True,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

#### band_part The tf.linalg.band_part method in TensorFlow is used to extract or modify the lower and upper triangular parts of a tensor while keeping the rest of the elements intact. It is commonly used in linear algebra operations and can be helpful in various tasks such as masking or manipulating triangular matrices.

The band_part method takes three parameters: input, num_lower, and num_upper. Here's what each parameter represents:

- input: This is the input tensor you want to apply the band operation to. It can be of any shape and data type.
- num_lower: It specifies the number of lower diagonals to keep (including the main diagonal). Diagonals below this number will be set to zero.
- num_upper: It specifies the number of upper diagonals to keep (including the main diagonal). Diagonals above this number will be set to zero.



In [47]:
input_tensor = tf.constant([[ 0,  1,  2, 3],
                            [-1,  3,  1, 2],
                            [ 3, -1,  2, 1],
                            [ 4,  5, -1, 5]])
print (input_tensor)

tf.Tensor(
[[ 0  1  2  3]
 [-1  3  1  2]
 [ 3 -1  2  1]
 [ 4  5 -1  5]], shape=(4, 4), dtype=int32)


In [49]:
tf.linalg.band_part(input_tensor, num_lower=1, num_upper=0) # we keep the main diagonal and the diagonal below it, while zeroing out the upper diagonal. 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 5]], dtype=int32)>

In [52]:
tf.linalg.band_part(input_tensor, num_lower=2, num_upper=0) # we keep the main diagonal and the 2 diagonals below it, while zeroing out the upper diagonal. 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  0,  0,  0],
       [-1,  3,  0,  0],
       [ 3, -1,  2,  0],
       [ 0,  5, -1,  5]], dtype=int32)>

In [54]:
tf.linalg.band_part(input_tensor, num_lower=2, num_upper=1) # we keep the main diagonal and the 2 diagonals below it and 1 diagonal above it

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  0,  0],
       [-1,  3,  1,  0],
       [ 3, -1,  2,  1],
       [ 0,  5, -1,  5]], dtype=int32)>

In [56]:
tf.linalg.band_part(input_tensor, num_lower=-1, num_upper=0) # we keep the lower traingular part only

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  0,  0,  0],
       [-1,  3,  0,  0],
       [ 3, -1,  2,  0],
       [ 4,  5, -1,  5]], dtype=int32)>

#### `expand_dims` and `squeeze`

In [58]:
input_tensor.shape

TensorShape([4, 4])

In [60]:
tf.expand_dims(input_tensor, axis=0).shape

TensorShape([1, 4, 4])

`squeeze`: Removes dimensions of size 1 from the shape of a tensor.


In [61]:
expanded = tf.expand_dims(input_tensor, axis=0)
expanded.shape

TensorShape([1, 4, 4])

In [62]:
tf.squeeze(expanded, axis=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  3,  1,  2],
       [ 3, -1,  2,  1],
       [ 4,  5, -1,  5]], dtype=int32)>

In [74]:
x = tf.constant([1,2,3,4,5])
print (x.shape) # 5

x = tf.expand_dims(x, axis=0)
print (x.shape)

x = tf.expand_dims(x, axis=0)
print (x.shape)

x = tf.expand_dims(x, axis=0)
print (x.shape)

x = tf.expand_dims(x, axis=0)
print (x.shape)

(5,)
(1, 5)
(1, 1, 5)
(1, 1, 1, 5)
(1, 1, 1, 1, 5)


In [75]:
print (x.shape)

(1, 1, 1, 1, 5)


In [76]:
### lets squeeze x back to original

for i in range(4):
    x = tf.squeeze(x, axis=0)
    print (x.shape)

(1, 1, 1, 5)
(1, 1, 5)
(1, 5)
(5,)


In [77]:
print (x)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


#### `pad` and `gather`

In [80]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 0,], [2, 1]])
# this basically means that the padding is to be applied 1 row up and 0 row below
# 2 rows left and 1 row right

In [81]:
tf.pad(tensor=t, paddings=paddings, mode="CONSTANT")

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0]], dtype=int32)>

In [87]:
t = tf.constant([[1, 2, 3, 4, 5, 6]])
t.shape

TensorShape([1, 6])

In [90]:
paddings = tf.constant([[1, 0], [0, 0]])


In [91]:
tf.pad(tensor=t, paddings=paddings, mode="CONSTANT")

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [1, 2, 3, 4, 5, 6]], dtype=int32)>

In [93]:
t = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(t.shape)
t[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [94]:
# we can do the same with gather

tf.gather(t, [0, 5, 3], axis=0) # axis 0 means 0,5,3 will be selected from 0th axis

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [96]:
params = tf.constant([[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]])

print(params.shape)
tf.gather(params, [2, 0], axis = 0) # select 2nd row and 0th row

(4, 3)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  5., 55.],
       [ 3.,  1., 21.]], dtype=float32)>

In [98]:
params = tf.constant([[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]])

print(params.shape)
tf.gather(params, [2, 0], axis = 1) # select 2nd col and 0th col

(4, 3)


<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[21.,  3.],
       [88.,  1.],
       [55.,  0.],
       [30.,  0.]], dtype=float32)>

In [99]:
params = tf.constant([
                        [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]
                       ])

print(params.shape)
tf.gather(params, [2, 0], axis = 0) # select 2nd and 0th tensors from 1st axis

(1, 4, 3)


<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 3.,  1., 21.],
        [ 1.,  3., 88.],
        [ 0.,  5., 55.],
        [ 0.,  2., 30.]]], dtype=float32)>

the shape is 1x4x3, so there are no 2nd tensors in 1st axis - so we have 0s

we have a 0th tensor, so that gets filled

In [100]:
params = tf.constant([
                        [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]
                       ])

print(params.shape)
tf.gather(params, [2, 0], axis = 1) # select 2nd and 0th tensors from 2nd axis

(1, 4, 3)


<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[ 0.,  5., 55.],
        [ 3.,  1., 21.]]], dtype=float32)>

In [103]:
params = tf.constant([
                      
                      [[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]], 
                      
                      [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]
                      
                      ])
print(params.shape)
tf.gather(params, [1, 0], axis = 0)

(2, 4, 3)


<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 3.,  1., 21.],
        [ 1.,  3., 88.],
        [ 0.,  5., 55.],
        [ 0.,  2., 30.]],

       [[ 0.,  1.,  2.],
        [10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]]], dtype=float32)>

In [104]:
params = tf.constant([
                      
                      [[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]], 
                      
                      [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]
                      
                      ])
print(params.shape)
tf.gather(params, [2, 0], axis = 1)

(2, 4, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]],

       [[ 0.,  5., 55.],
        [ 3.,  1., 21.]]], dtype=float32)>

Here we are working with 2nd axis

There are 2 tensors in the batch, so this will be done for both


```
for 2nd axis: [2,0]
- for the first tensor, [2,0]- [20., 21., 22.],
        [ 0.,  1.,  2.]
- for 2nd tensor, [2,0] - [[ 0.,  5., 55.],
        [ 3.,  1., 21.]]

```

In [105]:
params = tf.constant([
                      
                      [[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]], 
                      
                      [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]
                      
                      ])
print(params.shape)
tf.gather(params, [2, 0], axis = 2)

(2, 4, 3)


<tf.Tensor: shape=(2, 4, 2), dtype=float32, numpy=
array([[[ 2.,  0.],
        [12., 10.],
        [22., 20.],
        [32., 30.]],

       [[21.,  3.],
        [88.,  1.],
        [55.,  0.],
        [30.,  0.]]], dtype=float32)>