<a href="https://colab.research.google.com/github/ShaunakSen/Deep-Learning/blob/master/Deep_Learning_with_PyTorch_A_60_Minute_Blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with PyTorch: A 60 Minute Blitz

[link to tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)



## What is PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs

- a deep learning research platform that provides maximum flexibility and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.





In [0]:
from __future__ import print_function

import torch

Simple operations with tensors in Pytorch:

In [7]:
x = torch.empty(5, 3)
print(x)

# Construct a randomly initialized matrix:

x = torch.rand(5, 3)

print (x)

# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)

print(x)

# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])

print(x)

tensor([[2.9652e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.5554e-43],
        [2.1511e+23, 5.4171e-05, 1.3520e+22],
        [1.0812e-05, 1.6986e-07, 1.6926e+22],
        [5.4171e-05, 3.3560e-06, 2.5944e-01]])
tensor([[0.4885, 0.9567, 0.4418],
        [0.8493, 0.5637, 0.4951],
        [0.5968, 0.1448, 0.3345],
        [0.7567, 0.7668, 0.7266],
        [0.8468, 0.6290, 0.0301]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


We can also create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [8]:
x = x.new_ones(5, 3)

print (x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x = torch.randn_like(x, dtype=torch.float)

print(x)

# Get size

print(x.size())

tensor([[ 1.4667,  0.9827,  1.0788],
        [ 1.2486,  0.2936,  1.7310],
        [-0.5155,  1.0372,  0.6963],
        [-0.4524, -0.5691,  0.0402],
        [-0.1388, -0.4519,  0.6485]])
torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1



In [13]:
print (x)

y = torch.rand(5, 3)

print (y)

print (x + y)

# diff syntax:

# print (torch.add(x, y))


tensor([[ 1.4667,  0.9827,  1.0788],
        [ 1.2486,  0.2936,  1.7310],
        [-0.5155,  1.0372,  0.6963],
        [-0.4524, -0.5691,  0.0402],
        [-0.1388, -0.4519,  0.6485]])
tensor([[0.8182, 0.3427, 0.1410],
        [0.4064, 0.1530, 0.2190],
        [0.1948, 0.3130, 0.6729],
        [0.5562, 0.9651, 0.9468],
        [0.9648, 0.2941, 0.8028]])
tensor([[ 2.2849,  1.3254,  1.2198],
        [ 1.6550,  0.4466,  1.9500],
        [-0.3208,  1.3502,  1.3692],
        [ 0.1039,  0.3960,  0.9870],
        [ 0.8260, -0.1577,  1.4513]])


In [15]:
# Addition: providing an output tensor as argument

result = torch.empty(5, 3)

torch.add(x, y, out=result)

print(result)


# Addition: in-place

y.add_(x)
print(y)

tensor([[ 2.2849,  1.3254,  1.2198],
        [ 1.6550,  0.4466,  1.9500],
        [-0.3208,  1.3502,  1.3692],
        [ 0.1039,  0.3960,  0.9870],
        [ 0.8260, -0.1577,  1.4513]])
tensor([[ 2.2849,  1.3254,  1.2198],
        [ 1.6550,  0.4466,  1.9500],
        [-0.3208,  1.3502,  1.3692],
        [ 0.1039,  0.3960,  0.9870],
        [ 0.8260, -0.1577,  1.4513]])




```
Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
```


You can use standard NumPy-like indexing with all bells and whistles!


