<a href="https://colab.research.google.com/github/ShaunakSen/Deep-Learning/blob/master/Deep_Learning_with_PyTorch_A_60_Minute_Blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with PyTorch: A 60 Minute Blitz

[link to tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)



## What is PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs

- a deep learning research platform that provides maximum flexibility and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.





In [0]:
from __future__ import print_function

import torch

Simple operations with tensors in Pytorch:

In [6]:
x = torch.empty(5, 3)
print(x)

# Construct a randomly initialized matrix:

x = torch.rand(5, 3, 2)

print (x)

print (x[0][2])

# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)

print(x)

# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])

print(x)

tensor([[6.5976e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.9792e-01],
        [8.4265e-07, 2.5964e+20, 2.1352e+20],
        [5.4070e+22, 2.6216e+20, 1.3732e-05],
        [2.0317e+20, 2.6851e-06, 7.2279e-01]])
tensor([[[0.5939, 0.6729],
         [0.3609, 0.5540],
         [0.2579, 0.9895]],

        [[0.7434, 0.2126],
         [0.5648, 0.7895],
         [0.8500, 0.8280]],

        [[0.5653, 0.9563],
         [0.9316, 0.5325],
         [0.5092, 0.9978]],

        [[0.2056, 0.0341],
         [0.4145, 0.8109],
         [0.2204, 0.2199]],

        [[0.3376, 0.4541],
         [0.4973, 0.7542],
         [0.7418, 0.9274]]])
tensor([0.2579, 0.9895])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


We can also create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [8]:
x = torch.zeros(5, 3, dtype=torch.long)

print (x)

# new_ones will inherit the dtype of ip tensor (here int)

x = x.new_ones(5, 3)

print (x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [10]:
x = torch.randn_like(x, dtype=torch.float)

print(x)

# Get size

print(x.size())

tensor([[-0.5963,  0.8731,  0.7121],
        [-0.1791,  0.7933,  0.5135],
        [ 1.7168,  0.2044, -0.0895],
        [-0.2917,  1.5574,  0.0586],
        [ 0.8726,  0.3108, -0.8205]])
torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1



In [11]:
print (x)

y = torch.rand(5, 3)

print (y)

print (x + y)

# diff syntax:

# print (torch.add(x, y))


tensor([[-0.5963,  0.8731,  0.7121],
        [-0.1791,  0.7933,  0.5135],
        [ 1.7168,  0.2044, -0.0895],
        [-0.2917,  1.5574,  0.0586],
        [ 0.8726,  0.3108, -0.8205]])
tensor([[0.9069, 0.7296, 0.0556],
        [0.8576, 0.8320, 0.8246],
        [0.6868, 0.2866, 0.6829],
        [0.8622, 0.8356, 0.9357],
        [0.2815, 0.1011, 0.7992]])
tensor([[ 0.3106,  1.6028,  0.7677],
        [ 0.6785,  1.6253,  1.3381],
        [ 2.4035,  0.4910,  0.5934],
        [ 0.5705,  2.3931,  0.9943],
        [ 1.1541,  0.4120, -0.0214]])


In [12]:
# Addition: providing an output tensor as argument

result = torch.empty(5, 3)

print(result)

torch.add(x, y, out=result)

print(result)


# Addition: in-place

y.add_(x)
print(y)

tensor([[ 6.5977e-37,  0.0000e+00,  4.4842e-44],
        [ 0.0000e+00,         nan,  1.3381e+00],
        [ 8.4265e-07,  2.5964e+20,  2.1352e+20],
        [ 5.4070e+22,  2.6216e+20,  1.3732e-05],
        [ 2.0317e+20,  2.6851e-06, -2.1368e-02]])
tensor([[ 0.3106,  1.6028,  0.7677],
        [ 0.6785,  1.6253,  1.3381],
        [ 2.4035,  0.4910,  0.5934],
        [ 0.5705,  2.3931,  0.9943],
        [ 1.1541,  0.4120, -0.0214]])
tensor([[ 0.3106,  1.6028,  0.7677],
        [ 0.6785,  1.6253,  1.3381],
        [ 2.4035,  0.4910,  0.5934],
        [ 0.5705,  2.3931,  0.9943],
        [ 1.1541,  0.4120, -0.0214]])




```
Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
```


You can use standard NumPy-like indexing with all bells and whistles!




In [13]:
print (x[:, 1])

tensor([0.8731, 0.7933, 0.2044, 1.5574, 0.3108])


Resizing: If you want to resize/reshape tensor, you can use torch.view:



In [14]:
x = torch.randn(4, 4)

print (x)

y = x.view(16)

print (y, y.shape)

z = x.view(-1, 8) # the size -1 is inferred from other dimensions

print (z, z.shape)

# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)

print(x)

print(x.item())


tensor([[-4.0689e-01, -1.4886e+00, -1.2620e-01,  3.4432e-01],
        [-1.0363e+00, -1.4965e+00, -4.1733e-04, -2.1189e-01],
        [ 4.3286e-01,  3.8288e-01,  8.1407e-01,  1.2745e+00],
        [-3.7944e-01,  9.2872e-01,  7.8418e-01,  5.2352e-01]])
tensor([-4.0689e-01, -1.4886e+00, -1.2620e-01,  3.4432e-01, -1.0363e+00,
        -1.4965e+00, -4.1733e-04, -2.1189e-01,  4.3286e-01,  3.8288e-01,
         8.1407e-01,  1.2745e+00, -3.7944e-01,  9.2872e-01,  7.8418e-01,
         5.2352e-01]) torch.Size([16])
tensor([[-4.0689e-01, -1.4886e+00, -1.2620e-01,  3.4432e-01, -1.0363e+00,
         -1.4965e+00, -4.1733e-04, -2.1189e-01],
        [ 4.3286e-01,  3.8288e-01,  8.1407e-01,  1.2745e+00, -3.7944e-01,
          9.2872e-01,  7.8418e-01,  5.2352e-01]]) torch.Size([2, 8])
tensor([1.8307])
1.8307011127471924


## NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

**The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.**

### Converting a Torch Tensor to a NumPy Array


In [15]:
a = torch.ones(5)

print (a)

b = a.numpy()

print (b)

# See how the numpy array changed in value.

a.add_(1)

print(a)

print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np

a = np.ones(5)

b = torch.from_numpy(a)

np.add(a, 1, out=a)

print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

Tensors can be moved onto any device using the .to method.



In [0]:
# let us run this cell only if CUDA is available

# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
  device = torch.device("cuda") # a CUDA device object
  
  print (device)
  
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  
  x = x.to(device) # or just use strings ``.to("cuda")``
  z = x + y
  print(z)
  
  print(z.to(device="cpu",dtype=torch.double)) # ``.to`` can also change dtype together!
  

## AUTOGRAD: AUTOMATIC DIFFERENTIATION


Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

Let us see this in more simple terms with some examples.

### Tensor

`torch.Tensor` is the central class of the package. If you set its attribute `.requires_grad` as True, it starts to track all operations on it. When you finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into `.grad` attribute.

To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.

There’s one more class which is very important for autograd implementation - a Function.

Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

If you want to compute the derivatives, you can call .backward() on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.

In [17]:
# Create a tensor and set requires_grad=True to track computation with it

x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [18]:
y = x+2

print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y was created as a result of an operation, so it has a grad_fn.


In [19]:
print(y.grad_fn)

In [21]:
# Do more operations on y

z = y*y*3

print (z)

out = z.mean()

print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

In [31]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))

print(a)

print(a.requires_grad)

a.requires_grad_(True)

print(a.requires_grad)

b = (a*a).sum()

print(b)

print(b.grad_fn)

tensor([[  0.0887,   1.1763],
        [  0.2135, -29.3024]])
False
True
tensor(860.0660, grad_fn=<SumBackward0>)
