<a href="https://colab.research.google.com/github/ShaunakSen/Deep-Learning/blob/master/Deep_Learning_with_PyTorch_A_60_Minute_Blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with PyTorch: A 60 Minute Blitz

[link to tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)



## What is PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs

- a deep learning research platform that provides maximum flexibility and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.





In [0]:
from __future__ import print_function

import torch

Simple operations with tensors in Pytorch:

In [32]:
x = torch.empty(5, 3)
print(x)

# Construct a randomly initialized matrix:

x = torch.rand(5, 3)

print (x)

# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)

print(x)

# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])

print(x)

tensor([[1.0550e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.9500e+00],
        [1.7154e-07, 2.1439e-07, 1.6705e+22],
        [2.1954e-04, 2.0892e+20, 6.8627e-07],
        [4.3122e-08, 1.6918e-04, 1.4513e+00]])
tensor([[0.1279, 0.7575, 0.5538],
        [0.2163, 0.0678, 0.5580],
        [0.4737, 0.1055, 0.1549],
        [0.4087, 0.2972, 0.9590],
        [0.8846, 0.0217, 0.7626]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


We can also create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [33]:
x = x.new_ones(5, 3)

print (x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [34]:
x = torch.randn_like(x, dtype=torch.float)

print(x)

# Get size

print(x.size())

tensor([[ 1.2969, -0.9358,  0.5002],
        [ 1.0093, -0.6316,  1.1288],
        [ 0.0284,  0.2883, -0.1493],
        [-0.5257, -1.3940, -2.7181],
        [-0.3374, -0.9894,  1.3870]])
torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1



In [35]:
print (x)

y = torch.rand(5, 3)

print (y)

print (x + y)

# diff syntax:

# print (torch.add(x, y))


tensor([[ 1.2969, -0.9358,  0.5002],
        [ 1.0093, -0.6316,  1.1288],
        [ 0.0284,  0.2883, -0.1493],
        [-0.5257, -1.3940, -2.7181],
        [-0.3374, -0.9894,  1.3870]])
tensor([[0.0619, 0.5495, 0.2318],
        [0.3852, 0.2811, 0.5244],
        [0.2899, 0.7580, 0.1290],
        [0.0338, 0.0706, 0.5662],
        [0.3509, 0.6814, 0.8319]])
tensor([[ 1.3588, -0.3864,  0.7320],
        [ 1.3946, -0.3505,  1.6532],
        [ 0.3183,  1.0463, -0.0203],
        [-0.4918, -1.3233, -2.1519],
        [ 0.0134, -0.3080,  2.2189]])


In [36]:
# Addition: providing an output tensor as argument

result = torch.empty(5, 3)

torch.add(x, y, out=result)

print(result)


# Addition: in-place

y.add_(x)
print(y)

tensor([[ 1.3588, -0.3864,  0.7320],
        [ 1.3946, -0.3505,  1.6532],
        [ 0.3183,  1.0463, -0.0203],
        [-0.4918, -1.3233, -2.1519],
        [ 0.0134, -0.3080,  2.2189]])
tensor([[ 1.3588, -0.3864,  0.7320],
        [ 1.3946, -0.3505,  1.6532],
        [ 0.3183,  1.0463, -0.0203],
        [-0.4918, -1.3233, -2.1519],
        [ 0.0134, -0.3080,  2.2189]])




```
Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
```


You can use standard NumPy-like indexing with all bells and whistles!




In [37]:
print (x[:, 1])

tensor([-0.9358, -0.6316,  0.2883, -1.3940, -0.9894])


Resizing: If you want to resize/reshape tensor, you can use torch.view:



In [38]:
x = torch.randn(4, 4)

print (x)

y = x.view(16)

print (y, y.shape)

z = x.view(-1, 8) # the size -1 is inferred from other dimensions

print (z, z.shape)

# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)

print(x)

print(x.item())


tensor([[ 0.5503, -0.2049,  0.5096,  0.7812],
        [ 2.1719, -1.6890, -1.1916,  2.0088],
        [-1.0261,  1.9875,  1.1878,  0.1175],
        [ 0.1269,  0.1250, -0.5249, -0.2560]])
tensor([ 0.5503, -0.2049,  0.5096,  0.7812,  2.1719, -1.6890, -1.1916,  2.0088,
        -1.0261,  1.9875,  1.1878,  0.1175,  0.1269,  0.1250, -0.5249, -0.2560]) torch.Size([16])
tensor([[ 0.5503, -0.2049,  0.5096,  0.7812,  2.1719, -1.6890, -1.1916,  2.0088],
        [-1.0261,  1.9875,  1.1878,  0.1175,  0.1269,  0.1250, -0.5249, -0.2560]]) torch.Size([2, 8])
tensor([-0.6606])
-0.6605608463287354


## NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

**The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.**

### Converting a Torch Tensor to a NumPy Array


In [39]:
a = torch.ones(5)

print (a)

b = a.numpy()

print (b)

# See how the numpy array changed in value.

a.add_(1)

print(a)

print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [40]:
import numpy as np

a = np.ones(5)

b = torch.from_numpy(a)

np.add(a, 1, out=a)

print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

Tensors can be moved onto any device using the .to method.



In [0]:
# let us run this cell only if CUDA is available

# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
  device = torch.device("cuda") # a CUDA device object
  
  print (device)
  
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  
  x = x.to(device) # or just use strings ``.to("cuda")``
  z = x + y
  print(z)
  
  print(z.to(device="cpu",dtype=torch.double)) # ``.to`` can also change dtype together!
  